version: "3.9"
services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8881:8881"
    environment:
      - BASE_URL=http://localhost:8881
    depends_on:
      - frontend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
