services:
  myapp-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/html:ro
    networks:
      - main-network
    depends_on:
      - backend

  myapp-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8881:8881"
    environment:
      - BASE_URL=http://backend:8881 
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
