version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/html:ro
    networks:
      - main-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8881:8881"
    environment:
      - BASE_URL=http://localhost:8881
    depends_on:
      - frontend
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
