apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: backend
        image: green_api_myapp-backend:latest
        ports:
          - containerPort: 8881
        env:
          - name: BASE_URL
            value: http://localhost:8881
      - name: frontend
        image: green_api_myapp-frontend:latest
        ports:
          - containerPort: 80
